import { StyleSheet } from 'react-native';
import { COLORS } from '../Constants/theme';

// Sistema visual del inicio: superficies del mismo color que el fondo,
// sombras suaves y estados hundidos para conservar neomorfismo puro.
export const HomeStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 124,
  },
  contentCompact: {
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 26,
  },
  headerCopy: {
    flex: 1,
    paddingRight: 14,
  },
  eyebrow: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  greeting: {
    color: COLORS.textPrimary,
    fontSize: 25,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  greetingCompact: {
    fontSize: 22,
  },
  iconOuter: {
    backgroundColor: COLORS.background,
    borderRadius: 22,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  hero: {
    backgroundColor: COLORS.background,
    borderRadius: 28,
    marginBottom: 26,
    overflow: 'hidden',
    padding: 22,
  },
  heroCompact: {
    padding: 18,
  },
  heroLight: {
    borderColor: 'rgba(255,255,255,0.65)',
    borderLeftWidth: 1,
    borderTopWidth: 1,
    borderRadius: 28,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  heroTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heroKicker: {
    color: COLORS.primary,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 5,
  },
  heroTitle: {
    color: COLORS.textPrimary,
    fontSize: 21,
    fontWeight: '800',
    letterSpacing: -0.25,
  },
  heroTitleCompact: {
    fontSize: 19,
  },
  eggOuter: {
    backgroundColor: COLORS.background,
    borderRadius: 25,
  },
  eggInner: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 25,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  heroDescription: {
    color: COLORS.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 15,
  },
  heroAction: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: COLORS.background,
    borderRadius: 15,
    flexDirection: 'row',
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  heroActionText: {
    color: COLORS.primaryDark,
    fontSize: 12,
    fontWeight: '800',
    marginRight: 5,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitle: {
    color: COLORS.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  sectionLink: {
    color: COLORS.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  summaryGrid: {
    marginBottom: 16,
  },
  summaryError: {
    color: COLORS.error,
    fontSize: 11.5,
    fontWeight: '700',
    lineHeight: 16,
    marginBottom: 14,
    marginTop: -8,
    textAlign: 'center',
  },
  summaryOuter: {
    backgroundColor: COLORS.background,
    borderRadius: 21,
    marginBottom: 14,
    width: '100%',
  },
  summaryCard: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 21,
    flexDirection: 'row',
    minHeight: 92,
    overflow: 'hidden',
    paddingHorizontal: 17,
    paddingVertical: 14,
  },
  summaryLight: {
    borderColor: 'rgba(255,255,255,0.72)',
    borderLeftWidth: 1,
    borderRadius: 21,
    borderTopWidth: 1,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  summaryIconOuter: {
    backgroundColor: COLORS.background,
    borderRadius: 15,
    marginRight: 14,
  },
  summaryIcon: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  summaryValue: {
    color: COLORS.textPrimary,
    fontSize: 21,
    fontWeight: '800',
    marginTop: 3,
  },
  summaryValueCompact: {
    fontSize: 18,
    letterSpacing: -0.55,
  },
  summaryLabel: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  summaryCopy: {
    flex: 1,
    paddingRight: 10,
  },
  productList: {
    backgroundColor: COLORS.background,
    borderRadius: 25,
    marginBottom: 22,
    padding: 12,
  },
  productRow: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 18,
    flexDirection: 'row',
    marginBottom: 12,
    minHeight: 79,
    padding: 9,
  },
  productRowLast: {
    marginBottom: 0,
  },
  productImageShell: {
    backgroundColor: COLORS.background,
    borderRadius: 14,
  },
  productImage: {
    backgroundColor: COLORS.primaryLighter,
    borderRadius: 14,
    height: 57,
    width: 57,
  },
  productInitial: {
    alignItems: 'center',
    backgroundColor: COLORS.primaryLighter,
    borderRadius: 14,
    height: 57,
    justifyContent: 'center',
    width: 57,
  },
  productInfo: {
    flex: 1,
    marginHorizontal: 11,
  },
  productName: {
    color: COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 5,
  },
  productMeta: {
    color: COLORS.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  addOuter: {
    backgroundColor: COLORS.background,
    borderRadius: 15,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 15,
    height: 31,
    justifyContent: 'center',
    width: 31,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 22,
    marginBottom: 22,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  emptyTitle: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 10,
  },
  emptySubtitle: {
    color: COLORS.textSecondary,
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  actionList: {
    paddingBottom: 2,
  },
  primaryActionOuter: {
    backgroundColor: COLORS.background,
    borderRadius: 20,
    marginBottom: 14,
  },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 20,
    flexDirection: 'row',
    minHeight: 70,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  primaryActionIconOuter: {
    backgroundColor: COLORS.background,
    borderRadius: 15,
    marginRight: 13,
  },
  primaryActionIcon: {
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: 15,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  primaryActionCopy: {
    flex: 1,
    paddingRight: 8,
  },
  primaryActionTitle: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 3,
  },
  primaryActionSubtitle: {
    color: COLORS.textSecondary,
    fontSize: 11.5,
    fontWeight: '600',
  },
});

export default HomeStyles;